# This is a basic workflow to help you get started with Actions 

name: Build with malware dep

# Controls when the workflow will run
on:
  #push: 
  #  branches: [ "main" ]
  # Triggers the workflow on pull request events for the "main" branch
  #pull_request: 
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab sd
  workflow_dispatch:
    inputs:
      dep-name:
        description: 'Dep. Name'
        required: true
        default: 'octokit'
      from-dep-version:
        description: 'From Dep. Version'
        required: true
        default: '3.1.2'
      to-dep-version:
        description: 'To Dep. Version'
        required: true
        default: '4.0.0'
 
env:
  XY_USERNAME: ${{ secrets.XY_USERNAME_LABDEV }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD_LABDEV }}
  XY_URL: ${{ secrets.XY_URL_LABDEV }}
  XY_PRJ_NAME: GitHub-${{ github.event.repository.name }}
  PKG_NAME: ${{ github.event.inputs.dep-name }}
  FROM_PKG_VERSION: ${{ github.event.inputs.from-dep-version }}
  TO_PKG_VERSION: ${{ github.event.inputs.to-dep-version }}
  PKG_MALWARE: ${{ github.event.inputs.dep-malware }}
  NEW_DEP_VERSION: 4.0.3


jobs:
  # This workflow contains a single job called "xygeni_security_scan"
  build_with_malware_dep:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # ref: "refs/pull/${{ github.event.number }}/merge"
    # ref: ${{ github.event.pull_request.head.sha }}
  
    steps:


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out PR code
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          # This is to get the PR code instead of the repo code
          ref: ${{ github.event.pull_request.head.sha }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v4
        name: Checking out main code
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'


      - name: Upgrade to a malware dependency 
        run: |
          sed -i "s/3.1.2/$NEW_DEP_VERSION/g" ./package-lock.json
          #cp ${GITHUB_WORKSPACE}/package-lock.json.312 ${GITHUB_WORKSPACE}/package-lock.json
          grep $NEW_DEP_VERSION ./package-lock.json
    

      # Runs a set of commands using the runners shell 
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $XY_USERNAME -p $XY_PASSWORD -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner 
          
      # Runs a set of commands using the runners shell
      - name: Execution Xygeni Scanner (vuln)
        run: |
          set +e
          echo Executing Xygeni scan ....    
          ${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=critical --run="inventory,misconf,deps,suspectdeps,malware" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
          retVal=$?
          if [ $retVal -ne 0 ]; then
            echo "======================================="
            echo "Detected usage of Dep with Malware !!!! "
            echo " => Dep. Name:    $PKG_NAME"
            echo " => Dep. Version: $PKG_VERSION"
            echo "Breaking the build to avoid malware !!!! "
            echo "======================================="
            text="Detected usage of Dependency ($mw) with Malware !!!! "
            #echo "::error file=app.js,line=10,col=15::$text"
            echo "::error $mw::$text"
            text="Breaking the build to avoid malware infection !!!! "
            #echo "::error file=app.js,line=10,col=15::$text"
            echo "::error $mw::$text"
          fi
          exit $retVal
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
