# This is a basic workflow to help you get started with Actions 

name: Change Status

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab sd
  workflow_dispatch:
    inputs:
      dep-name:
        description: 'Dep. Name'
        required: true
        default: 'octokit'
      dep-version:
        description: 'Dep. Version'
        required: true
        default: '3.1.2'  
      dep-status:
        type: choice
        description: New Status
        options: 
        - confirmed_by_xygeni
        - confirmed_malware
        - safe





env:
  XY_USERNAME: ${{ secrets.XY_USERNAME_LABDEV }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD_LABDEV }}
  XY_URL: ${{ secrets.XY_URL_LABDEV }}
  XY_PRJ_NAME: GitHub-${{ github.event.repository.name }}
  DEP_NAME: ${{ github.event.inputs.dep-name }}
  DEP_VERSION: ${{ github.event.inputs.dep-version }}
  DEP_STATUS: ${{ github.event.inputs.dep-status }}




jobs:
  # This workflow contains a single job called "xygeni_security_scan"
  xygeni_cicd_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # ref: "refs/pull/${{ github.event.number }}/merge"
    # ref: ${{ github.event.pull_request.head.sha }}
  
    steps:

      - name: Cat event 
        run: |
          echo EVENT  ${{ github.event_name }}
          echo DEP_NAME $DEP_NAME
          echo DEP_VERSION $DEP_VERSION
          echo DEP_STATUS $DEP_STATUS
          exit 1
          

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out PR code
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          # This is to get the PR code instead of the repo code
          ref: ${{ github.event.pull_request.head.sha }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v4
        name: Checking out main code
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'



      # Runs a set of commands using the runners shell 
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $XY_USERNAME -p $XY_PASSWORD -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner 
          
      # Runs a set of commands using the runners shell
      - name: Execution Xygeni Scanner (vuln)
        run: |
          set +e
          echo Executing Xygeni scan ....    
          ${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=critical --run="inventory,misconf,deps,suspectdeps,malware" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
          retVal=$?
          if [ $retVal -ne 0 ]; then
            echo "======================================="
            echo "Malware detected !!!! "
            echo " => Dep. Name:    $PKG_NAME"
            echo " => Dep. Version: $PKG_VERSION"
            echo "======================================="
          fi
          exit $retVal
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
